### ISSUE TITLE
Information leak?

### ISSUE THREAD

**Issue by chaoyan1037** [kaist-amsg/LocalRetro#2]
Hi, some people report that your method can not reproduce reported results with canonical test input as preprocessed in [RetroXpert](https://github.com/uta-smile/RetroXpert). Have you run your model with data processed by RetroXpert?

**Comment by shuan4638** [comment]
@chaoyan1037 Yes, I also noticed the issue of data leakage as mentioned in RetroXpert. We did run our model with data processed by RetroXpert using [canonicalize_products.py](https://github.com/uta-smile/RetroXpert/blob/main/canonicalize_products.py#L20), the results are identical with the reported results.
Since our model is graph-based approach and the bond representation is directed, the data leakage should not be an issue in our approach.

**Comment by chaoyan1037** [comment]
That is great! Thanks for the confirmation!
